---
- name: 'update packages.'
  become: yes
  apt:
    upgrade: yes
    update_cache: yes
    cache_valid_time: 100000
- name: remove deps we don't need
  become: yes
  apt:
    autoremove: yes
- name: install the deps
  become: yes
  apt:
    name: ['nodejs', 'npm']
    state: latest
    update_cache: yes
- name: install pm2
  become: yes
  npm:
    name: pm2
    global: yes
    state: latest
    production: yes
- name: Copy files
  become: true
  copy:
    src: /root/project/artifact.tar.gz
    dest: /home/ubuntu/artifact.tar.gz
- name: Unarchive
  become: true
  shell : |
      cd /home/ubuntu/
      tar xvzf artifact.tar.gz -C .
- name: start app
  become: yes
  shell: |
    pm2 delete all
    pm2 start npm -- start
  environment:
    ENVIRONMENT: production
    TYPEORM_CONNECTION: "{{ lookup('env', 'TYPEORM_CONNECTION') }}"
    TYPEORM_MIGRATIONS_DIR: "./migrations"
    TYPEORM_MIGRATIONS: "./migrations/*.js"
    TYPEORM_ENTITIES: "./modules/domain/**/*.entity.js"
    TYPEORM_HOST: "{{ lookup('env', 'TYPEORM_HOST') }}"
    TYPEORM_PORT: "{{ lookup('env', 'TYPEORM_PORT') }}"
    TYPEORM_USERNAME: "{{ lookup('env', 'TYPEORM_USERNAME') }}"
    TYPEORM_PASSWORD: "{{ lookup('env', 'TYPEORM_PASSWORD') }}"
    TYPEORM_DATABASE: "{{ lookup('env', 'TYPEORM_DATABASE') }}"